apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zaif-pvc
  namespace: zaif-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
